### ISSUE TITLE
error for constructing hop-2 subgraphs

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [muhanzhang/IGMC#22]
Hello,

I encountered an error when trying to construct 2-hop subgraphs by running ``` python Main.py --data-name flixster --epochs 40 --testing --ensemble --hop 2```

See error message below. Let me know if you need any further information. Thank you!

```
Namespace(ARR=0.001, adj_dropout=0.2, asin_pop_thres=25, batch_size=50, continue_from=None, data_appendix='', data_name='flixster', data_seed=1234, debug=False, dynamic_test=False, dynamic_train=False, dynamic_val=False, ensemble=True, epochs=40, force_undirected=False, hop='2', keep_old=False, lr=0.001, lr_decay_factor=0.1, lr_decay_step_size=50, max_nodes_per_hop=10000, max_test_num=None, max_train_num=None, max_val_num=None, multiply_by=1, no_train=False, num_relations=5, ratio=1.0, reprocess=False, sample_ratio=1.0, save_appendix='', save_interval=10, seed=1, standard_rating=False, test_freq=1, testing=True, transfer='', use_features=False, user_thres=140, visualize=False)
Command line input: python Main.py --data-name flixster --epochs 40 --testing --ensemble --hop 2
 is saved.
number of users =  2341
number of item =  2956
User features shape: (3000, 3000)
Item features shape: (3000, 3000)
All ratings are:
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
#train: 23556, #val: 4712, #test: 2617
Processing...
Enclosing subgraph extraction begins...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:03<00:00,  9.79it/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/igmc/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ubuntu/anaconda3/envs/igmc/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/ubuntu/proj/IGMC/util_functions.py", line 217, in subgraph_extraction_labeling
    v_fringe, u_fringe = neighbors(u_fringe, Arow), neighbors(v_fringe, Acol)
  File "/home/ubuntu/proj/IGMC/util_functions.py", line 302, in neighbors
    return set(A[list(fringe)].indices)
  File "/home/ubuntu/proj/IGMC/util_functions.py", line 61, in __getitem__
    indices = np.concatenate(self.indices[col_selector])
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Main.py", line 337, in <module>
    max_num=args.max_train_num
  File "/home/ubuntu/proj/IGMC/util_functions.py", line 91, in __init__
    super(MyDataset, self).__init__(root)
  File "/home/ubuntu/anaconda3/envs/igmc/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/ubuntu/anaconda3/envs/igmc/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/ubuntu/anaconda3/envs/igmc/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/home/ubuntu/proj/IGMC/util_functions.py", line 106, in process
    self.class_values, self.parallel)
  File "/home/ubuntu/proj/IGMC/util_functions.py", line 190, in links2subgraphs
    results = results.get()
  File "/home/ubuntu/anaconda3/envs/igmc/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/ubuntu/anaconda3/envs/igmc/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ubuntu/anaconda3/envs/igmc/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/ubuntu/proj/IGMC/util_functions.py", line 217, in subgraph_extraction_labeling
    v_fringe, u_fringe = neighbors(u_fringe, Arow), neighbors(v_fringe, Acol)
  File "/home/ubuntu/proj/IGMC/util_functions.py", line 302, in neighbors
    return set(A[list(fringe)].indices)
  File "/home/ubuntu/proj/IGMC/util_functions.py", line 61, in __getitem__
    indices = np.concatenate(self.indices[col_selector])
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:03<00:00,  9.64it/s]
python Main.py --data-name flixster --epochs 40 --testing --ensemble --hop 2  12.19s user 1.34s system 130% cpu 10.410 total       
```

**Comment by muhanzhang** [comment]
Hi @Chen-Cai-OSU! Thanks for finding this bug. It is due to empty fringe when querying neighbors. I have fixed this bug in the new [version](https://github.com/muhanzhang/IGMC/commit/3f94460e3cfa78d39a4a299eafe0fc112d0a4849).

**Comment by Chen-Cai-OSU** [comment]
Thank you!
