### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by ZzyChris97** [muhanzhang/IGMC#31]
When i run the model with the ml_1m and met this error

**Comment by ZzyChris97** [comment]
Traceback (most recent call last):
  File "/root/code/python/share/IGMC-master/Main.py", line 389, in <module>
    model = IGMC(
  File "/root/code/python/share/IGMC-master/models.py", line 177, in __init__
    super(IGMC, self).__init__(
  File "/root/code/python/share/IGMC-master/models.py", line 22, in __init__
    self.convs.append(gconv(dataset.num_features, latent_dim[0]))
  File "/usr/local/anaconda3/envs/geometric/lib/python3.9/site-packages/torch_geometric/data/dataset.py", line 115, in num_features
    return self.num_node_features
  File "/usr/local/anaconda3/envs/geometric/lib/python3.9/site-packages/torch_geometric/data/dataset.py", line 104, in num_node_features
    data = self[0]
  File "/usr/local/anaconda3/envs/geometric/lib/python3.9/site-packages/torch_geometric/data/dataset.py", line 198, in __getitem__
    data = self.get(self.indices()[idx])
  File "/usr/local/anaconda3/envs/geometric/lib/python3.9/site-packages/torch_geometric/data/dataset.py", line 91, in indices
    return range(self.len()) if self._indices is None else self._indices
  File "/usr/local/anaconda3/envs/geometric/lib/python3.9/site-packages/torch_geometric/data/dataset.py", line 63, in len
    raise NotImplementedError
NotImplementedError

**Comment by vinaykudari** [comment]
In Dataset class we need to override len() function. 
I was able to fix this issue by changing the function name from `__len__` to `len` in `MyDynamicDataset` class



```
# from this
def __len__(self):
    return len(self.links[0])

# to this
def len(self):
    return len(self.links[0])
```

**Comment by yangmingming629** [comment]
> When i run the model with the ml_1m and met this error

I also met this error when I run the model under the flixster, and ml_100k datasets.
